### ISSUE TITLE
Sometimes $_POST is empty

### ISSUE THREAD

**Issue by rachidaitouaissi** [deliciousbrains/wp-background-processing#110]
While using the plugin, I encountered a small issue related to the timeout, I noticed that setting the timeout to 0.01 seconds caused some intermittent problems, resulting in an empty $_POST within the handle() function.

After some troubleshooting, I found that increasing the timeout to a more reasonable value, such as +1 second, resolved the issue completely. 

Thank you for your hard work and dedication to maintaining this plugin.

**Comment by ianmjones** [comment]
Thanks to @kagg-design and his #103  PR, this will be resolved in the next release when we'll return the timeout to the default of 5 seconds.
