### ISSUE TITLE
Using on Plugin Activation/Deactivation

### ISSUE THREAD

**Issue by joneslloyd** [deliciousbrains/wp-background-processing#21]
Hi there,

I want to call an asynchronous function upon Activation and Deactivation of my plugin (two different classes that extend "WP_Async_Request").

I'm finding however that these actions don't get called when dispatched.

Any idea if I'm missing something obvious, or whether execution would get halted for whatever reason?

**Comment by ianmjones** [comment]
This is a rather late response, but at the point of activation and deactivation I suspect that you'll have a timing issue whereby you can't be sure that the `WP_Async_Request` subclass is available to be instantiated by the plugin to receive the dispatched request.
