### ISSUE TITLE
Question: sub-processes

### ISSUE THREAD

**Issue by Surgeonito** [deliciousbrains/wp-background-processing#26]
Are there any constraints or limitations that could make impossible designing a background process that contains a set of background processes?
I've made two attempts to make and had a problem with initiating subprocesses. 
Did anyone try anything similar?

**Comment by filtah** [comment]
Yeah im getting the same - After running a process, I want to call another to perform another set of tasks, but the sub process is not executing. not getting any errors in the log either, so looks like the class is getting called but not sure why its not running..

**Comment by markjaquith** [comment]
Make sure you're not instantiating the sub-task from within the main task.

I have it working where a once-off request is triggered which does an expensive data query which then kicks off a batch of expensive processing requests on the data.

**Comment by ianmjones** [comment]
Closing ancient issue. :smile:
