### ISSUE TITLE
Please tell us max queue insert to database 

### ISSUE THREAD

**Issue by nhoctanker** [deliciousbrains/wp-background-processing#49]
To day i check  wp_queue Put in insert only 3 queue database

exmple 
I have  4 user : A , B , C ,D

wp_queue(userA)
wp_queue(userB)
wp_queue(userC)
wp_queue(userD) // D not work

Realy code

wp_quue(New NOTIFICATIONALLUSER(users));

In notificationAllUser

foreach(users as user)
 wp_queue(new WP_Job_Notification($this->key, $this->message, $this->data,$user->ID,'promotion'));

but only three queue add to database

**Comment by ianmjones** [comment]
Closing ancient issue. :smile:
