### ISSUE TITLE
Class 'WP_Async_Request' not found 

### ISSUE THREAD

**Issue by topbloke5590** [deliciousbrains/wp-background-processing#53]
Hi

I have installed the example plugin, but getting the following error:

Fatal error: Class 'WP_Async_Request' not found in C:\xampp\htdocs\WP-CRM\wp-content\plugins\wp-background-processing-example-master\async-requests\class-example-request.php on line 3

Any help would be great as I am new to this.  There are not other errors in the logs, but whole site stops working.

Thanks in advance.

**Comment by markjaquith** [comment]
You have to load the classes first.

I recommend using Composer and:

`require __DIR__ . '/vendor/autoload.php';`

**Comment by rachidaitouaissi** [comment]
Thank you for this great library, could you please help me!

I can't activate the example plugin! Fatal error:  Class 'WP_Async_Request' not found...

@markjaquith markjaquith   How to use composer and require __DIR__ . '/vendor/autoload.php';

Please help I need to use this  library

Thank you

**Comment by OlafEichstaedt** [comment]
if you are not familiar with autoload, you can simply use

`require_once 'path_to_wher_you_stored_wa-async-request.php';`

**Comment by dariuszwit** [comment]
Hello,

I had the same issue. All answers are correct, but to be more specific:

1. Run the command below in the plugin directory: ...\wp-content\plugins\wp-background-processing-example-master
`composer require deliciousbrains/wp-background-processing`
A new directory should appear: vendor
`wp-content\plugins\wp-background-processing-example-master\vendor`

2. Paste the line below into the file: example-plugin.php, as the first line in init function.
`require_once plugin_dir_path( __FILE__ ) . 'vendor/autoload.php';`

You will get:
`public function init() {`
`    require_once plugin_dir_path( __FILE__ ) . 'vendor/autoload.php';`
`    require_once plugin_dir_path( __FILE__ ) . 'class-logger.php';`
`    require_once plugin_dir_path( __FILE__ ) . 'async-requests/class-example-request.php';`
`    require_once plugin_dir_path( __FILE__ ) . 'background-processes/class-example-process.php';`

Regards,
Dariusz
