### ISSUE TITLE
for the WP_Async_Request how to get the data received from the ajax call

### ISSUE THREAD

**Issue by cas1993per** [deliciousbrains/wp-background-processing#56]
sorry i'm new to the PDO and i cant figure out how to get the data received from the AJAX call and its working fine and print out what i want to log file but i want it to be available through global variable in my code once the data received.

**Comment by cas1993per** [comment]
`class Example_Background_Processing {

	protected $process_single;

	public function __construct($name,$from,$to,$interval ) {
		$this->name = $name;
		$this->from = $from;
		$this->to = $to;
		$this->interval = $interval;
		add_action( 'plugins_loaded', array( $this, 'init' ) );
		add_action( 'admin_bar_menu', array( $this, 'admin_bar' ), 100 );
		add_action( 'init', array( $this, 'process_handler' ) );
	}

	public function init() {
		require_once plugin_dir_path( __FILE__ ) . 'async-requests/class-example-request.php';
		$this->process_single = new WP_Example_Request();
	}

	public function admin_bar( $wp_admin_bar ) {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$wp_admin_bar->add_menu( array(
			'id'    => 'example-plugin',
			'title' => __( 'Process', 'example-plugin' ),
			'href'  => wp_nonce_url( admin_url( '?process=single'), 'process' ),
		) );
	}

	public function process_handler() {
		if ( 'single' === $_GET['process'] ) {
			$this->handle_single();
		}
	}

	protected function handle_single() {
		$this->process_single->data( array( 'name' => $this->name, 'from' => $this->from, 'to' => $this->to, 'interval' => $this->interval ) )->dispatch();
	}
}

$myobj = new Example_Background_Processing('AAPL','2000-01-01','2000-01-12','1d');`

`class WP_Example_Request extends WP_Async_Request {

	protected $action = 'example_request';

	protected function handle() {
		$message = getYahoo( $_POST['name'], $_POST['from'], $_POST['to'], $_POST['interval'] );
		file_put_contents(WP_PLUGIN_DIR . '/logs.log', '['.date(DATE_RFC2822).'] '.$message.PHP_EOL , FILE_APPEND | LOCK_EX);
	}
}`

**Comment by cas1993per** [comment]
class WP_Example_Request extends WP_Async_Request {

	protected $action = 'example_request';

	protected function handle() {
		$message = getYahoo( $_POST['name'], $_POST['from'], $_POST['to'], $_POST['interval'] );
		file_put_contents(WP_PLUGIN_DIR . '/logs.log', '['.date(DATE_RFC2822).'] '.$message.PHP_EOL , FILE_APPEND | LOCK_EX);
	}
}

class Example_Background_Processing {

	protected $process_single;

	public function __construct($name,$from,$to,$interval ) {
		$this->name = $name;
		$this->from = $from;
		$this->to = $to;
		$this->interval = $interval;
		add_action( 'plugins_loaded', array( $this, 'init' ) );
		add_action( 'admin_bar_menu', array( $this, 'admin_bar' ), 100 );
		add_action( 'init', array( $this, 'process_handler' ) );
	}

	public function init() {
		require_once plugin_dir_path( __FILE__ ) . 'async-requests/class-example-request.php';
		$this->process_single = new WP_Example_Request();
	}

	public function admin_bar( $wp_admin_bar ) {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$wp_admin_bar->add_menu( array(
			'id'    => 'example-plugin',
			'title' => __( 'Process', 'example-plugin' ),
			'href'  => wp_nonce_url( admin_url( '?process=single'), 'process' ),
		) );
	}

	public function process_handler() {
		if ( 'single' === $_GET['process'] ) {
			$this->handle_single();
		}
	}

	protected function handle_single() {
		$this->process_single->data( array( 'name' => $this->name, 'from' => $this->from, 'to' => $this->to, 'interval' => $this->interval ) )->dispatch();
	}
}

$myobj = new Example_Background_Processing('AAPL','2000-01-01','2000-01-12','1d');

**Comment by cas1993per** [comment]
each time I want to receive symbol data i create new instance using this line `$myobj = new Example_Background_Processing('AAPL','2000-01-01','2000-01-12','1d');` and then find way to get the data once received to my code and use it in my plugin.
is that logic correct?
Thank you in advance

**Comment by ianmjones** [comment]
Closing ancient issue. :smile:
