### ISSUE TITLE
Maximum execution time reached on a WP Background Processing

### ISSUE THREAD

**Issue by ntreyssat** [deliciousbrains/wp-background-processing#64]
I've used `WP Background Processing` to execute really long request, for example inserting 1000 users.

I guess I was wrong by assuming that it split really long task in multiple WP-Crons because I reach the maximum execution time (30 seconds) in `wp_hash_password()` (called on user creation).

I have to split long task myself on multiple queue items ?

**Comment by arobbins** [comment]
I have a similar situation and need to split the longer tasks into many shorter ones. I've also had to request that my users increase their PHP `max_execution_time` value.

It would be great if there was a workaround for this.

**Comment by ntreyssat** [comment]
This library is already helpful to process long task by splitting them in multiples queue items. I'm not sure it's possible at WP Background Processing level to separate long tasks in smaller sub-tasks.

**Comment by polevaultweb** [comment]
You would need to check for memory or timeout issues inside your task method, and return the $item. This means the job is put back on the queue, and initiated in a new request.

You would need to add data to the $item array so you can keep track of where you are in your processing.

eg.

```
protected function $task( $item ) {
	...
	if ( $this->time_exceeded() || $this->memory_exceeded() ) {
		// Batch limits reached.
		$item['pointer'] = ftell( $file );

		return $item;
	}
	...
}
```

**Comment by arobbins** [comment]
@polevaultweb 

Thanks! I should have thought about doing this, makes sense.

If you have a second, would you mind elaborating on this part? `$item['pointer'] = ftell( $file );`

I'm confused where `$file` is coming from and why the entire line is needed. Can I just return `$item` instead?

**Comment by polevaultweb** [comment]
Sorry @arobbins that was an example from my own use case. I'm uploading a file in chunks and need to pass the position of the file I was at before the task ran out of memory/timed-out

**Comment by polevaultweb** [comment]
The example there is basically save any data you need for the next iteration of the job back to the $item

**Comment by arobbins** [comment]
Perfect, makes sense. Thanks again.
