### ISSUE TITLE
Debug Async request with PHPStorm?

### ISSUE THREAD

**Issue by Luc45** [deliciousbrains/wp-background-processing#65]
Hi,

Thanks for your contribution to the community!

Is it possible to debug async classes with PHPStorm? I add my breakpoints but they don't stop when making async requests.

**Comment by sawwd** [comment]
Hi,

You can add:

`Header set Set-Cookie "XDEBUG_SESSION=PHPSTORM"` to your .htaccess and add `xdebug.ide_key='PHPSTORM'` to your php.ini and it should fire work.

If it doesn't work for any reason add this `xdebug.remote_autostart=1` too to your php.ini

**Comment by omgwtfwow** [comment]
Will depend on your environment. But for example, a local VM running WordPress (on osx):

php.ini:

`zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"
xdebug.remote_enable=true
xdebug.remote_autostart=1
;xdebug.remote_connect_back=0 //connect_back didn't work for me on OSX, it does on Windows
xdebug.remote_host=192.168.1.2 // the IP address of your PHPStorm/IDE machine
xdebug.remote_port=9000 //This port must be open to your virtual machine
xdebug.remote_handler=dbgp
xdebug.profiler_enable=1
xdebug.profiler_output_dir=/tmp
xdebug.idekey="PHPSTORM" //or whatever you are using`

Replace the URL of the request with your PHP storm machine, I include the XDEBUG_SESSION query string:
`$url = "http://192.168.1.2/?XDEBUG_SESSION=PHPSTORM"`

You can also add the cookie in your request, for example with wp_remote_post:

`				$cookie = new WP_Http_Cookie('XDEBUG_SESSION=PHPSTORM;path=/;');

				//POST
				$response = wp_remote_post(
					$url, array(
						'method'      => 'POST',
						'timeout'     => 5,
						'redirection' => 5,
						'httpversion' => '1.0',
						'blocking'    => false,
						'headers'     => array(),
						'body'        => array($body),
						'cookies'     => array($cookie)
					)
				);
`

If you're using a browser extension to trigger the debug, you need to also change its settings to use the PHPSTORM session key.

I've only tested this with background tasks, not processes, but don't see why it wouldn't work. You might need to extend the xdebug session timeout if it doesn't.

**Comment by polevaultweb** [comment]
Thanks @omgwtfwow 👍
