### ISSUE TITLE
The dispatch method not working 'wp_loaded' some action

### ISSUE THREAD

**Issue by 9brada6** [deliciousbrains/wp-background-processing#67]
Hi... I want some help from someone who can help me... I don't understand why, but the async function is working fine if I create the object and use it in an early action, like creating directly in functions.php or called via 'wp_loaded' action or 'init'. However if I call it from 'wp' action it won't work. 

```
class WP_Example_Request extends WP_Async_Request {

	protected $action = 'example_request';

	protected function handle() {
		error_log('is working');
	}

}

function makeItWork(){
	$obj = new WP_Example_Request();
	$obj->dispatch();
}
```

If i use `add_action( 'wp_loaded', 'makeItWork' );` will work, if i change to `add_action( 'wp', 'makeItWork' );` will not work. Even if i change to 'parse_request' action, the one after 'wp_loaded' will not work, so wp_loaded is the last of what will work. ... anyone know what I'm doing wrong?

I also changed the timeout and the return of the dispatch() method to something like this:
```
			$output = wp_remote_post( esc_url_raw( $url ), $args );
			error_log( serialize($output) );
			return $output;
```

The error log will show something like this(so the dispatch method work, however it will not run my function ):
[Sun Feb 10 22:58:40.447691 2019] [php7:notice] [pid 15924:tid 1896] [client 192.168.0.200:58319] a:5:{s:7:"headers";a:0:{}s:4:"body";s:0:"";s:8:"response";a:2:{s:4:"code";b:0;s:7:"message";b:0;}s:7:"cookies";a:0:{}s:13:"http_response";N;}

Note: My server is on the same machine I code, but I connect via private IP under router, and not localhost.

**Comment by w33zy** [comment]
Going from the old responses here, I think it is because `wp` is too early in the WP load cycle to call the `wp_ajax_` action that this code depends on.
