### ISSUE TITLE
How Does WP Background Processing Compare To Sidekiq?

### ISSUE THREAD

**Issue by robskrob** [deliciousbrains/wp-background-processing#68]
I'm a little confused as to how this works. I have set up queueing systems using [sidekiq](https://github.com/mperham/sidekiq) before and this, `wp-background-processing` seems very different. In Sidekiq, there's a redis queue and my application enqueues messages to a queue in redis. Along side the web processes there's another forever running process that consumes messages off of the queue and runs them, assigning certain messages to certain background Jobs (Ruby Classes). In short there are two processes: a web process and a background process.

1. How many processes are there with `wp-background-processing`? 
2. Is the background process and the web process that powers my wordpress site the same PHP process? 
3. What queue is being used? In Sidekiq, usually the queue technology is Redis. 
4. If I have a 1500 expensive HTTP requests hitting my wordpress app and I want to enqueue, let's say, 1500 background jobs -- one for each request -- to save off an expensive operation to an API or a database, is my Apache process still blocked? In the sidekiq example, it would not be blocked because the web process (Puma / Nginx) would just offload a message to a redis queue and let the sidekiq process deal with it when it needs to, one message at a time (well actually multiple messages at a time because Ruby is multi threaded).

**Comment by w33zy** [comment]
@robskrob 

This maybe a bit late but let me say that this and Sidekiq are worlds and worlds apart. They are not even in the same universe. This code is just some cleverness with the WordPress API to push potentially running code in the WP_CRON system for later processing.

**Comment by robskrob** [comment]
@w33zy thank you for your reply. Yes, after thoroughly digging through `wp-background-processing` I have learned that this project just leverages `wp-cron` and schedules a job to run at "now" with `time()`.

I was hopping to get a timely response from someone but instead I had to roll up my sleeves and dig through the source code -- oh well.

**Comment by w33zy** [comment]
Yeah, I figured. Yesterday, I spent the entire day digging through this code base to figure out why it wasn't working with PSR auto-loading, hence my insight.

**Comment by ianmjones** [comment]
> @robskrob
> 
> This maybe a bit late but let me say that this and Sidekiq are worlds and worlds apart. They are not even in the same universe.

True, https://github.com/deliciousbrains/wp-queue is probably a little closer, but not really.

> This code is just some cleverness with the WordPress API to push potentially running code in the WP_CRON system for later processing.

Not quite, WP-Cron is only used for a healthcheck to kick off processing a queue that has stopped for some reason, e.g. server reboot.

Otherwise, the background processing is kicked off by your code and continues with chained background processes until there is nothing else to be processed. When the next chunk of items are needing to be processed they are queued up and the background process started again. If more items are added to the queue while a background process is running it'll pick them up too.
