### ISSUE TITLE
Publish new vendor name on packagist

### ISSUE THREAD

**Issue by njbarrett** [deliciousbrains/wp-background-processing#70]
Hi guys,
Is it possible for you to publish this package under the new vendor name?
This will help resolve https://github.com/wp-media/wp-rocket/issues/1633

**Comment by smilingpeanut** [comment]
+1

**Comment by kl3sk** [comment]
Interested in publishing too

**Comment by dsturm** [comment]
Hey @deliciousbrains, please look into this one.

**Comment by dsturm** [comment]
> Hi guys,
> Is it possible for you to publish this package under the new vendor name?
> This will help resolve [wp-media/wp-rocket#1633](https://github.com/wp-media/wp-rocket/issues/1633)

Nevermind, looks like @wp-media forked this repo and did an alternate versioning. So this is not really an issue of @deliciousbrains but @wp-media.

**Comment by kl3sk** [comment]
@wp-media found a solution, but this package is not published anyway on packagist.

**Comment by polevaultweb** [comment]
The vendor has been amended and it's now on packagist.org https://packagist.org/packages/deliciousbrains/wp-background-processing
