### ISSUE TITLE
Unexpected entry

### ISSUE THREAD

**Issue by AnthoRdev** [deliciousbrains/wp-background-processing#73]
Hello there,
I'm wondering what the firsts lines means in this batch, `N`?:
```a:466:{
	i:6;N;
	i:52;N;
	i:55;N;
	i:56;N;
	i:59;N;
	i:225;s:25:"RESI-805759-update-463567";
	i:226;s:19:"RESI-805764-import-";
	i:227;s:19:"RESI-805765-import-";
	i:228;s:19:"RESI-805766-import-";
	i:229;s:19:"RESI-805772-import-";
	i:230;s:19:"RESI-805783-import-";
	}
```
What is creating this entries with "N". I think it's not me, cause if it was that should be like that : `i:6;s:1:"N";` right?

Thanks for reading, have a good day !
Anthony

**Comment by tw2113** [comment]
I assume `null`

**Comment by kagg-design** [comment]
@AnthoRdev You can read about serialization here: https://www.phpinternalsbook.com/php5/classes_objects/serialization.html

**Comment by AnthoRdev** [comment]
Thank you. I forgot to close that issue :) But of course, you both, are right! Thanks!

**Comment by AnthoRdev** [comment]
Thank you. I forgot to close that issue :) But of course, you both, are right! Thanks!
