### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by BenceSzalai** [deliciousbrains/wp-background-processing#76]
Hi!

Could you please clarify the licensing?

Apparently the license in `composer.json` has been changed from `GPLv2+` to `GPL-2.0-only` in 1f070aab however in `README.md` it still say `GPLv2+`.

This pretty much means that the repo can be used under GPL v2 or later, but the composer package can only be used under GPL v2, which is a possible case imo, but seems unlikely to be intended.

Please clarify! Thanks!

**Comment by polevaultweb** [comment]
Fixing this to be `GPL-2.0-or-later`, thanks for the heads up @BenceSzalai
