### ISSUE TITLE
How can I make it run from a script only instantiating WP through wp-load.php ?

### ISSUE THREAD

**Issue by Hmastery** [deliciousbrains/wp-background-processing#79]
WP_Background_Process only works if the function executing it is located in the functions.php file it's is very frustrating.

I have Cron Jobs that I execute on my own, when I want them to rely on wordpress/woocommerce features I just use:
`require_once(__DIR__.'/../shop/wp-load.php');`
Allowing me to use whatever is in functions.php or some core features of both WC and WP.

But in this specific case when I'm trying to execute the code extending WP_Background_Process it just won't work.
The invoked function is executed but the content of task method will never be executed.

Has someone a fully working piece of code executed outside of functions.php which works? I just spent 12 hours straight on this, I think I'm going nut.

**Comment by ezequiel9** [comment]
I have been trying to set this exactly how it says in the docs and doesn't work at all.. 

It doesn't create any new table, 
It doesn't add into options table anything like cron or event
I cannot see the queue in the list
I don't know how to trigger the tasks manually to check if its works or not.. 

I am also using it outside of functions.php

**Comment by ezequiel9** [comment]
I know!! 
This plugin uses AJAX to execute the script, then your class needs to be instantiated  in somewhere 
in addition to your dispatch action!

**Comment by Hmastery** [comment]
Do you have any working code example with instruction over where to put the file and how to call the initiating function? :))

**Comment by ezequiel9** [comment]
Your class

```php
class TaskCreateCustomer extends WP_Background_Process {

	/**
	 * @var string
	 */
	protected $action = 'task_create_customer';

	/**
	 * Task method
	 * @param mixed $customerID
	 * @return mixed
	 */
	protected function task( $customerID ) {
                $someWrapperAPI = new Wrapper();
		$success = $someWrapperAPI->updateCustomer($customerID);
		if ($success) {
		        // maybe log success
                        return false; // FALSE removes the row from the queue in theory
                }
		// maybe log the error		
	}

	/**
	 * Complete
	 */
	protected function complete() {
		parent::complete();
		// Add other task on complete maybe.. 
	}

}
```

Instance you function in somewhere to let WP know that you have an action ajax to register. Maybe in functions.php or some other global class in your project.

```php
new new TaskCreateCustomer();
```


Your use...

```php
$task = new TaskCreateCustomer();
$task->push_to_queue( $customerID )->save()->dispatch();
```

**Comment by ianmjones** [comment]
Closing ancient issue. :smile:
