### ISSUE TITLE
After some file relocation, the nonce could not be verified anymore

### ISSUE THREAD

**Issue by rvencu** [deliciousbrains/wp-background-processing#80]
I had the library working for a while then I decided to move files in a different folder structure. did composer remove, composer require and moved my files accordingly

After this, the function `check_ajax_referer` refused to validate the nonce.

**Comment by rvencu** [comment]
I think the problem is that I am initially calling an API endpoint, where I am authenticating with Basic authentication.

I can see that the WP_Async_Request class tries to pass the $_COOKIE object in an effort to preserve the user session but in my case there are no cookies so the session is not preserved. Thus the nonce is not available on the receiving end.

**Comment by ianmjones** [comment]
Closing ancient issue. :smile: (but https://github.com/deliciousbrains/wp-background-processing#basicauth might help)
