### ISSUE TITLE
Not really ASync because of wp_remote_post()

### ISSUE THREAD

**Issue by Cyrille37** [deliciousbrains/wp-background-processing#82]
Hello
While digging the code I see that `WP_Async_Request::dispatch()` use `wp_remote_post()` to launch the job. But `wp_remote_post()` will wait the request answer before returning, that took the necessary job's run time. So it is not asynchronous ?

Have I miss something ?

Best regards
Cyrille.

**Comment by kagg-design** [comment]
No, it does not wait, Please look at https://github.com/deliciousbrains/wp-background-processing/blob/2cbee1abd1b49e1133cd8f611df4d4fc5a8b9800/classes/wp-async-request.php#L142

**Comment by Cyrille37** [comment]
Yeah! Thanks a lot, I didn't know about this.

With the use of this timeout option, perhaps you have to add a `ignore_user_abort(false);` somewhere to make php ignore the client disconnection.

Regards.
