### ISSUE TITLE
get_memory_limit function assumes php.ini memory is in "M"

### ISSUE THREAD

**Issue by toddlevy-jambase** [deliciousbrains/wp-background-processing#95]
We recently changed our memory limit from a value expressed in "M" (e.g. 2048M) to a value expressed in "G" (e.g. 4G).

After making this change, the queue stopped processing as expected.

We believe it's because the native `memory_get_usage()` function is returning a value in M and so when it gets compared to a result from `get_memory_limit()` -- where the `ini_get( 'memory_limit' )` call comes back in G, and is then converted to an integer -- the memory limit always seems too low and the memory_exceeded returns true.

		/**
		 * Memory exceeded
		 *
		 * Ensures the worker process never exceeds 80%
		 * of the maximum allowed PHP memory.
		 *
		 * @return bool
		 */
		protected function memory_exceeded() {
			$memory_limit   = $this->get_memory_limit() * 0.8; // 80% of max memory
			$current_memory = memory_get_usage( true );
			$return         = false;

			if ( $current_memory >= $memory_limit ) {
				$return = true;
			}

			return apply_filters( 'http_feed_worker_memory_exceeded', $return );
		}

		/**
		 * Get memory limit
		 *
		 * @return int
		 */
		protected function get_memory_limit() {
			if ( function_exists( 'ini_get' ) ) {
				$memory_limit = ini_get( 'memory_limit' );
			} else {
				// Sensible default
				$memory_limit = '128M';
			}

			if ( ! $memory_limit || -1 == $memory_limit ) {
				// Unlimited, set to 32GB
				$memory_limit = '32000M';
			}

			return intval( $memory_limit ) * 1024 * 1024;
		}

**Comment by ianmjones** [comment]
You must be using an old version of the library, this was fixed in [v1.0.2](https://github.com/deliciousbrains/wp-background-processing/releases/tag/1.0.2) in response to #77.
