### ISSUE TITLE
Add class namespaces

### ISSUE THREAD

**Issue by SebKay** [deliciousbrains/wp-background-processing#98]
Hi,

I'm a big fan of the plugin and have been using it for years. Thank you for all your hard work!

As you probably know, using Composer in a WordPress plugin or theme can conflict with other plugins when they've also using Composer.

I've run into an issue where sometimes the version of `wp-background-processing` I'm using is different to the one another plugins pulls in, causing a problem where my code is using the version pulled in by the other plugin, not the version I've pulled in.

Are you open to adding namespace to the classes in this package? I'm more than happy to attempt a PR for this myself.

If so it'll mean I, and others, can use tools such as [Imposter](https://github.com/TypistTech/imposter) to prefix the class namespaces which will prevent this issue.

**Comment by mostafasoufi** [comment]
I'd prefer to [Scope](https://github.com/humbug/php-scoper) the namespace if you installing the package via Composer. However, if you are installing the library manually, you can add your custom namespace to the following two classes:

```
<?php

namespace WP_SMS\Library\BackgroundProcessing;

/**
 * WP Async Request
 *
 * @package WP-Background-Processing
 */

/**
 * Abstract WP_Async_Request class.
 *
 * @abstract
 */
abstract class WP_Async_Request {
```


```
<?php

namespace WP_SMS\Library\BackgroundProcessing;

/**
 * WP Background Process
 *
 * @package WP-Background-Processing
 */

/**
 * Abstract WP_Background_Process class.
 *
 * @abstract
 * @extends WP_Async_Request
 */
abstract class WP_Background_Process extends WP_Async_Request {
```
